apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-demo.fullname" . }}-stage
  labels:
    {{- include "go-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "go-demo.selectorLabels" . | nindent 4 }}
    {{- if eq .Values.productionSlot "blue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }}
